# Conda environment for Gammapy tutorials
# Install:    conda env create -f environment.yml
# Update:     conda env update -f environment.yml
# Activate:   source activate gammapy-tutorial
# Deactivate: source deactivate

name: gammapy-tutorial

channels:
  - conda-forge
  - sherpa

dependencies:
  - python==3.6
  - ipython
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - cython
  - numpy==1.13
  - pandas
  - astropy
  - regions
  - click
  - pyyaml
  - scipy
  - matplotlib
  - scikit-image
  - uncertainties
  - healpy
  - reproject
  - photutils
  - sherpa
  - iminuit

  - pip:
    - git+https://github.com/gammapy/gammapy.git#egg=gammapy
